// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type CategoryDocumentDataSlicesSlice = never;

/**
 * Content for Category documents
 */
interface CategoryDocumentData {
    /**
     * Slice Zone field in *Category*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: category.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices: prismic.SliceZone<CategoryDocumentDataSlicesSlice> /**
     * Meta Description field in *Category*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A brief summary of the page
     * - **API ID Path**: category.meta_description
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */;
    meta_description: prismic.KeyTextField;

    /**
     * Meta Image field in *Category*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: category.meta_image
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    meta_image: prismic.ImageField<never>;

    /**
     * Meta Title field in *Category*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A title of the page used for social media and search engines
     * - **API ID Path**: category.meta_title
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    meta_title: prismic.KeyTextField;
}

/**
 * Category document from Prismic
 *
 * - **API ID**: `category`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CategoryDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
    Simplify<CategoryDocumentData>,
    'category',
    Lang
>;

/**
 * Item in *FooterMenu → Navigation*
 */
export interface FootermenuDocumentDataNavigationItem {
    /**
     * Menu Item field in *FooterMenu → Navigation*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: footermenu.navigation[].menu_item
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    menu_item: prismic.ContentRelationshipField<'homepage' | 'page' | 'posts'>;

    /**
     * Menu Label field in *FooterMenu → Navigation*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footermenu.navigation[].menu_label
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    menu_label: prismic.KeyTextField;
}

/**
 * Content for FooterMenu documents
 */
interface FootermenuDocumentData {
    /**
     * Navigation field in *FooterMenu*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: footermenu.navigation[]
     * - **Tab**: Primary Menu
     * - **Documentation**: https://prismic.io/docs/field#group
     */
    navigation: prismic.GroupField<Simplify<FootermenuDocumentDataNavigationItem>>;
}

/**
 * FooterMenu document from Prismic
 *
 * - **API ID**: `footermenu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FootermenuDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
    Simplify<FootermenuDocumentData>,
    'footermenu',
    Lang
>;

/**
 * Item in *GlobalOptions → Address*
 */
export interface GlobaloptionsDocumentDataAddressItem {
    /**
     * Address Line One field in *GlobalOptions → Address*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: globaloptions.address[].address_line_one
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    address_line_one: prismic.KeyTextField;

    /**
     * Address Line Two field in *GlobalOptions → Address*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: globaloptions.address[].address_line_two
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    address_line_two: prismic.KeyTextField;

    /**
     * Town/City field in *GlobalOptions → Address*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: globaloptions.address[].town_city
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    town_city: prismic.KeyTextField;

    /**
     * County field in *GlobalOptions → Address*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: globaloptions.address[].county
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    county: prismic.KeyTextField;

    /**
     * Postcode field in *GlobalOptions → Address*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: globaloptions.address[].postcode
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    postcode: prismic.KeyTextField;

    /**
     * Country field in *GlobalOptions → Address*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: globaloptions.address[].country
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    country: prismic.KeyTextField;
}

/**
 * Content for GlobalOptions documents
 */
interface GlobaloptionsDocumentData {
    /**
     * Logo field in *GlobalOptions*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: globaloptions.logo
     * - **Tab**: Global Options
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    logo: prismic.ImageField<never>;

    /**
     * Email Address field in *GlobalOptions*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Add contact email address
     * - **API ID Path**: globaloptions.email_address
     * - **Tab**: Global Options
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    email_address: prismic.KeyTextField;

    /**
     * Phone Number field in *GlobalOptions*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Add contact phone number
     * - **API ID Path**: globaloptions.phone_number
     * - **Tab**: Global Options
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    phone_number: prismic.KeyTextField;

    /**
     * Address field in *GlobalOptions*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: globaloptions.address[]
     * - **Tab**: Global Options
     * - **Documentation**: https://prismic.io/docs/field#group
     */
    address: prismic.GroupField<Simplify<GlobaloptionsDocumentDataAddressItem>>;

    /**
     * Copyright field in *GlobalOptions*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: globaloptions.copyright
     * - **Tab**: Global Options
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    copyright: prismic.KeyTextField;
}

/**
 * GlobalOptions document from Prismic
 *
 * - **API ID**: `globaloptions`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GlobaloptionsDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
    Simplify<GlobaloptionsDocumentData>,
    'globaloptions',
    Lang
>;

type HomepageDocumentDataSlicesSlice = never;

type HomepageDocumentDataSlices1Slice =
    | SchemaFaqSlice
    | SchemaWebsiteSiteLinksSlice
    | SchemaArticleSlice
    | SchemaEventSlice
    | SchemaOrganisationSlice;

type HomepageDocumentDataSlices2Slice =
    | TextBlockSlice
    | LeadGenFormSlice
    | ContactFormSlice
    | ClientGridSlice
    | FeaturesGridSlice
    | HerotextSlice
    | TestDeleteSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
    /**
     * Slice Zone field in *Homepage*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
     * Meta Title field in *Homepage*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A title of the page used for social media and search engines
     * - **API ID Path**: homepage.meta_title
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */;
    meta_title: prismic.KeyTextField;

    /**
     * Meta Description field in *Homepage*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A brief summary of the page
     * - **API ID Path**: homepage.meta_description
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    meta_description: prismic.KeyTextField;

    /**
     * Meta Image field in *Homepage*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.meta_image
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    meta_image: prismic.ImageField<never>;

    /**
     * Slice Zone field in *Homepage*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.slices1[]
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices1: prismic.SliceZone<HomepageDocumentDataSlices1Slice> /**
     * Slice Zone field in *Homepage*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.slices2[]
     * - **Tab**: Page Builder
     * - **Documentation**: https://prismic.io/docs/field#slices
     */;
    slices2: prismic.SliceZone<HomepageDocumentDataSlices2Slice>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
    Simplify<HomepageDocumentData>,
    'homepage',
    Lang
>;

type PageDocumentDataSlicesSlice = never;

type PageDocumentDataSlices1Slice = SchemaEventSlice | SchemaOrganisationSlice;

type PageDocumentDataSlices2Slice =
    | TextBlockSlice
    | ContactFormSlice
    | LeadGenFormSlice
    | HerotextSlice
    | TestDeleteSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
    /**
     * Parent field in *Page*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: page.category
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    category: prismic.ContentRelationshipField<'page'>;

    /**
     * Slice Zone field in *Page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
     * Meta Title field in *Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A title of the page used for social media and search engines
     * - **API ID Path**: page.meta_title
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */;
    meta_title: prismic.KeyTextField;

    /**
     * Meta Description field in *Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A brief summary of the page
     * - **API ID Path**: page.meta_description
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    meta_description: prismic.KeyTextField;

    /**
     * Meta Image field in *Page*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: page.meta_image
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    meta_image: prismic.ImageField<never>;

    /**
     * Slice Zone field in *Page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices1[]
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices1: prismic.SliceZone<PageDocumentDataSlices1Slice> /**
     * Slice Zone field in *Page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices2[]
     * - **Tab**: Page Builder
     * - **Documentation**: https://prismic.io/docs/field#slices
     */;
    slices2: prismic.SliceZone<PageDocumentDataSlices2Slice>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
    Simplify<PageDocumentData>,
    'page',
    Lang
>;

type PostDocumentDataSlicesSlice = never;

type PostDocumentDataSlices1Slice = SchemaArticleSlice;

type PostDocumentDataSlices2Slice = TextBlockSlice;

/**
 * Content for Post documents
 */
interface PostDocumentData {
    /**
     * Page Title field in *Post*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: post.page_title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    page_title: prismic.TitleField;

    /**
     * Post Date field in *Post*
     *
     * - **Field Type**: Date
     * - **Placeholder**: *None*
     * - **API ID Path**: post.post_date
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#date
     */
    post_date: prismic.DateField;

    /**
     * Listing Image field in *Post*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: post.listing_image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    listing_image: prismic.ImageField<never>;

    /**
     * Slice Zone field in *Post*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: post.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices: prismic.SliceZone<PostDocumentDataSlicesSlice> /**
     * Meta Title field in *Post*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A title of the page used for social media and search engines
     * - **API ID Path**: post.meta_title
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */;
    meta_title: prismic.KeyTextField;

    /**
     * Meta Description field in *Post*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A brief summary of the page
     * - **API ID Path**: post.meta_description
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    meta_description: prismic.KeyTextField;

    /**
     * Meta Image field in *Post*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: post.meta_image
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    meta_image: prismic.ImageField<never>;

    /**
     * Slice Zone field in *Post*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: post.slices1[]
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices1: prismic.SliceZone<PostDocumentDataSlices1Slice> /**
     * Slice Zone field in *Post*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: post.slices2[]
     * - **Tab**: Page Builder
     * - **Documentation**: https://prismic.io/docs/field#slices
     */;
    slices2: prismic.SliceZone<PostDocumentDataSlices2Slice>;
}

/**
 * Post document from Prismic
 *
 * - **API ID**: `post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PostDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
    Simplify<PostDocumentData>,
    'post',
    Lang
>;

type PostsDocumentDataSlicesSlice = never;

type PostsDocumentDataSlices1Slice = SchemaEventSlice | SchemaOrganisationSlice;

/**
 * Content for Posts documents
 */
interface PostsDocumentData {
    /**
     * Slice Zone field in *Posts*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: posts.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices: prismic.SliceZone<PostsDocumentDataSlicesSlice> /**
     * Meta Title field in *Posts*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A title of the page used for social media and search engines
     * - **API ID Path**: posts.meta_title
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */;
    meta_title: prismic.KeyTextField;

    /**
     * Meta Description field in *Posts*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A brief summary of the page
     * - **API ID Path**: posts.meta_description
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    meta_description: prismic.KeyTextField;

    /**
     * Meta Image field in *Posts*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: posts.meta_image
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    meta_image: prismic.ImageField<never>;

    /**
     * Slice Zone field in *Posts*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: posts.slices1[]
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices1: prismic.SliceZone<PostsDocumentDataSlices1Slice>;
}

/**
 * Posts document from Prismic
 *
 * - **API ID**: `posts`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PostsDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
    Simplify<PostsDocumentData>,
    'posts',
    Lang
>;

/**
 * Item in *PrimaryMenu → Navigation*
 */
export interface PrimarymenuDocumentDataNavigationItem {
    /**
     * Menu Item field in *PrimaryMenu → Navigation*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: primarymenu.navigation[].menu_item
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    menu_item: prismic.ContentRelationshipField<'homepage' | 'page' | 'posts'>;

    /**
     * Menu Label field in *PrimaryMenu → Navigation*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: primarymenu.navigation[].menu_label
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    menu_label: prismic.KeyTextField;
}

/**
 * Content for PrimaryMenu documents
 */
interface PrimarymenuDocumentData {
    /**
     * Navigation field in *PrimaryMenu*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: primarymenu.navigation[]
     * - **Tab**: Primary Menu
     * - **Documentation**: https://prismic.io/docs/field#group
     */
    navigation: prismic.GroupField<Simplify<PrimarymenuDocumentDataNavigationItem>>;
}

/**
 * PrimaryMenu document from Prismic
 *
 * - **API ID**: `primarymenu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PrimarymenuDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
    Simplify<PrimarymenuDocumentData>,
    'primarymenu',
    Lang
>;

/**
 * Content for SocialPlatforms documents
 */
interface SocialplatformsDocumentData {
    /**
     * Facebook field in *SocialPlatforms*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Add Facebook handle
     * - **API ID Path**: socialplatforms.facebook
     * - **Tab**: Social Platforms
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    facebook: prismic.KeyTextField;

    /**
     * Twitter field in *SocialPlatforms*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Add Twitter handle
     * - **API ID Path**: socialplatforms.twitter
     * - **Tab**: Social Platforms
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    twitter: prismic.KeyTextField;

    /**
     * Instagram field in *SocialPlatforms*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Add Instagram handle
     * - **API ID Path**: socialplatforms.instagram
     * - **Tab**: Social Platforms
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    instagram: prismic.KeyTextField;

    /**
     * LinkedIn field in *SocialPlatforms*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Add LinkedIn handle
     * - **API ID Path**: socialplatforms.linkedin
     * - **Tab**: Social Platforms
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    linkedin: prismic.KeyTextField;

    /**
     * Tiktok field in *SocialPlatforms*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Add Tiktok handle
     * - **API ID Path**: socialplatforms.tiktok
     * - **Tab**: Social Platforms
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    tiktok: prismic.KeyTextField;
}

/**
 * SocialPlatforms document from Prismic
 *
 * - **API ID**: `socialplatforms`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SocialplatformsDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
    Simplify<SocialplatformsDocumentData>,
    'socialplatforms',
    Lang
>;

export type AllDocumentTypes =
    | CategoryDocument
    | FootermenuDocument
    | GlobaloptionsDocument
    | HomepageDocument
    | PageDocument
    | PostDocument
    | PostsDocument
    | PrimarymenuDocument
    | SocialplatformsDocument;

/**
 * Primary content in *ClientGrid → Items*
 */
export interface ClientGridSliceDefaultItem {
    /**
     * Client Logo field in *ClientGrid → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: client_grid.items[].client_logo
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    client_logo: prismic.ImageField<never>;
}

/**
 * Default variation for ClientGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: ClientGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ClientGridSliceDefault = prismic.SharedSliceVariation<
    'default',
    Record<string, never>,
    Simplify<ClientGridSliceDefaultItem>
>;

/**
 * Slice variation for *ClientGrid*
 */
type ClientGridSliceVariation = ClientGridSliceDefault;

/**
 * ClientGrid Shared Slice
 *
 * - **API ID**: `client_grid`
 * - **Description**: ClientGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ClientGridSlice = prismic.SharedSlice<'client_grid', ClientGridSliceVariation>;

/**
 * Default variation for ContactForm Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSliceDefault = prismic.SharedSliceVariation<'default', Record<string, never>, never>;

/**
 * Slice variation for *ContactForm*
 */
type ContactFormSliceVariation = ContactFormSliceDefault;

/**
 * ContactForm Shared Slice
 *
 * - **API ID**: `contact_form`
 * - **Description**: ContactForm
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSlice = prismic.SharedSlice<'contact_form', ContactFormSliceVariation>;

/**
 * Primary content in *FeaturesGrid → Primary*
 */
export interface FeaturesGridSliceDefaultPrimary {
    /**
     * Title field in *FeaturesGrid → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: features_grid.primary.title
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    title: prismic.TitleField;

    /**
     * Tagline field in *FeaturesGrid → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: features_grid.primary.tagline
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    tagline: prismic.RichTextField;

    /**
     * Button Text field in *FeaturesGrid → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: features_grid.primary.button_text
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    button_text: prismic.KeyTextField;

    /**
     * Button Link field in *FeaturesGrid → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: features_grid.primary.button_link
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    button_link: prismic.LinkField;
}

/**
 * Primary content in *FeaturesGrid → Items*
 */
export interface FeaturesGridSliceDefaultItem {
    /**
     * Title field in *FeaturesGrid → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: features_grid.items[].title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField;

    /**
     * Description field in *FeaturesGrid → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: features_grid.items[].description
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    description: prismic.KeyTextField;

    /**
     * Icon field in *FeaturesGrid → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: features_grid.items[].icon
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    icon: prismic.ImageField<never>;
}

/**
 * Default variation for FeaturesGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: FeaturesGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturesGridSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<FeaturesGridSliceDefaultPrimary>,
    Simplify<FeaturesGridSliceDefaultItem>
>;

/**
 * Slice variation for *FeaturesGrid*
 */
type FeaturesGridSliceVariation = FeaturesGridSliceDefault;

/**
 * FeaturesGrid Shared Slice
 *
 * - **API ID**: `features_grid`
 * - **Description**: FeaturesGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturesGridSlice = prismic.SharedSlice<'features_grid', FeaturesGridSliceVariation>;

/**
 * Primary content in *HeroText → Primary*
 */
export interface HerotextSliceDefaultPrimary {
    /**
     * Theme field in *HeroText → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: herotext.primary.theme
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    theme: prismic.SelectField<'Dark' | 'Light'>;

    /**
     * Prefix field in *HeroText → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: herotext.primary.prefix
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    prefix: prismic.KeyTextField;

    /**
     * Title field in *HeroText → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: herotext.primary.title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField;

    /**
     * Tagline field in *HeroText → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: herotext.primary.tagline
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    tagline: prismic.KeyTextField;
}

/**
 * Primary content in *HeroText → Items*
 */
export interface HerotextSliceDefaultItem {
    /**
     * Button Text field in *HeroText → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: herotext.items[].button_text
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    button_text: prismic.KeyTextField;

    /**
     * Button Link field in *HeroText → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: herotext.items[].button_link
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    button_link: prismic.LinkField;
}

/**
 * Default variation for HeroText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HerotextSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<HerotextSliceDefaultPrimary>,
    Simplify<HerotextSliceDefaultItem>
>;

/**
 * Primary content in *HeroText → Primary*
 */
export interface HerotextSliceHeroTextWithVideoPrimary {
    /**
     * Theme field in *HeroText → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: herotext.primary.theme
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    theme: prismic.SelectField<'Dark' | 'Light'>;

    /**
     * Prefix field in *HeroText → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: herotext.primary.prefix
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    prefix: prismic.KeyTextField;

    /**
     * Title field in *HeroText → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: herotext.primary.title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField;

    /**
     * Tagline field in *HeroText → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: herotext.primary.tagline
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    tagline: prismic.KeyTextField;

    /**
     * Video File field in *HeroText → Primary*
     *
     * - **Field Type**: Link to Media
     * - **Placeholder**: *None*
     * - **API ID Path**: herotext.primary.video_file
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    video_file: prismic.LinkToMediaField;
}

/**
 * Primary content in *HeroText → Items*
 */
export interface HerotextSliceHeroTextWithVideoItem {
    /**
     * Button Text field in *HeroText → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: herotext.items[].button_text
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    button_text: prismic.KeyTextField;

    /**
     * Button Link field in *HeroText → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: herotext.items[].button_link
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    button_link: prismic.LinkField;
}

/**
 * Hero – With Video variation for HeroText Slice
 *
 * - **API ID**: `heroTextWithVideo`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HerotextSliceHeroTextWithVideo = prismic.SharedSliceVariation<
    'heroTextWithVideo',
    Simplify<HerotextSliceHeroTextWithVideoPrimary>,
    Simplify<HerotextSliceHeroTextWithVideoItem>
>;

/**
 * Slice variation for *HeroText*
 */
type HerotextSliceVariation = HerotextSliceDefault | HerotextSliceHeroTextWithVideo;

/**
 * HeroText Shared Slice
 *
 * - **API ID**: `herotext`
 * - **Description**: HeroText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HerotextSlice = prismic.SharedSlice<'herotext', HerotextSliceVariation>;

/**
 * Default variation for LeadGenForm Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LeadGenFormSliceDefault = prismic.SharedSliceVariation<'default', Record<string, never>, never>;

/**
 * Slice variation for *LeadGenForm*
 */
type LeadGenFormSliceVariation = LeadGenFormSliceDefault;

/**
 * LeadGenForm Shared Slice
 *
 * - **API ID**: `lead_gen_form`
 * - **Description**: LeadGenForm
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LeadGenFormSlice = prismic.SharedSlice<'lead_gen_form', LeadGenFormSliceVariation>;

/**
 * Primary content in *SchemaArticle → Primary*
 */
export interface SchemaArticleSliceDefaultPrimary {
    /**
     * Type field in *SchemaArticle → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: Article
     * - **API ID Path**: schema_article.primary.type
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    type: prismic.SelectField<'Article' | 'BlogPosting' | 'BlogArticle', 'filled'>;

    /**
     * URL field in *SchemaArticle → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: schema_article.primary.url
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    url: prismic.KeyTextField;

    /**
     * Headline field in *SchemaArticle → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: schema_article.primary.headline
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    headline: prismic.KeyTextField;

    /**
     * Image URL field in *SchemaArticle → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: schema_article.primary.imageUrl
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    imageUrl: prismic.KeyTextField;

    /**
     * Date published field in *SchemaArticle → Primary*
     *
     * - **Field Type**: Timestamp
     * - **Placeholder**: *None*
     * - **API ID Path**: schema_article.primary.datePublished
     * - **Documentation**: https://prismic.io/docs/field#timestamp
     */
    datePublished: prismic.TimestampField;

    /**
     * Date modified field in *SchemaArticle → Primary*
     *
     * - **Field Type**: Timestamp
     * - **Placeholder**: *None*
     * - **API ID Path**: schema_article.primary.dateModified
     * - **Documentation**: https://prismic.io/docs/field#timestamp
     */
    dateModified: prismic.TimestampField;

    /**
     * Author type field in *SchemaArticle → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: Person
     * - **API ID Path**: schema_article.primary.authorType
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    authorType: prismic.SelectField<'Person' | 'Organization', 'filled'>;

    /**
     * Author name field in *SchemaArticle → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: schema_article.primary.authorName
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    authorName: prismic.KeyTextField;

    /**
     * Publisher name field in *SchemaArticle → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: schema_article.primary.publisherName
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    publisherName: prismic.KeyTextField;

    /**
     * Publisher logo URL field in *SchemaArticle → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: schema_article.primary.publisherLogoUrl
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    publisherLogoUrl: prismic.KeyTextField;
}

/**
 * Default variation for SchemaArticle Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SchemaArticleSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<SchemaArticleSliceDefaultPrimary>,
    never
>;

/**
 * Slice variation for *SchemaArticle*
 */
type SchemaArticleSliceVariation = SchemaArticleSliceDefault;

/**
 * SchemaArticle Shared Slice
 *
 * - **API ID**: `schema_article`
 * - **Description**: SchemaArticle
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SchemaArticleSlice = prismic.SharedSlice<'schema_article', SchemaArticleSliceVariation>;

/**
 * Primary content in *SchemaEvent → Primary*
 */
export interface SchemaEventSliceDefaultPrimary {
    /**
     * Name field in *SchemaEvent → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: schema_event.primary.name
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    name: prismic.KeyTextField;

    /**
     * Description field in *SchemaEvent → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: schema_event.primary.description
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    description: prismic.KeyTextField;

    /**
     * Image URl field in *SchemaEvent → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: schema_event.primary.image
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    image: prismic.KeyTextField;

    /**
     * Attendance Mode field in *SchemaEvent → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: Mixed
     * - **API ID Path**: schema_event.primary.attendance_mode
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    attendance_mode: prismic.SelectField<'Mixed' | 'Offline' | 'Online', 'filled'>;

    /**
     * Status field in *SchemaEvent → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: Scheduled
     * - **API ID Path**: schema_event.primary.status
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    status: prismic.SelectField<'Scheduled' | 'Moved online' | 'Postponed' | 'Rescheduled' | 'Cancelled', 'filled'>;

    /**
     * Start date & time field in *SchemaEvent → Primary*
     *
     * - **Field Type**: Timestamp
     * - **Placeholder**: *None*
     * - **API ID Path**: schema_event.primary.startDate
     * - **Documentation**: https://prismic.io/docs/field#timestamp
     */
    startDate: prismic.TimestampField;

    /**
     * End date & time field in *SchemaEvent → Primary*
     *
     * - **Field Type**: Timestamp
     * - **Placeholder**: *None*
     * - **API ID Path**: schema_event.primary.endDate
     * - **Documentation**: https://prismic.io/docs/field#timestamp
     */
    endDate: prismic.TimestampField;

    /**
     * Location name field in *SchemaEvent → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: schema_event.primary.locationName
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    locationName: prismic.KeyTextField;

    /**
     * Street Address field in *SchemaEvent → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: schema_event.primary.locationStreetAddress
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    locationStreetAddress: prismic.KeyTextField;

    /**
     * City field in *SchemaEvent → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: schema_event.primary.locationAddressLocality
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    locationAddressLocality: prismic.KeyTextField;

    /**
     * State/Province/Region field in *SchemaEvent → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Required
     * - **API ID Path**: schema_event.primary.locationAddressRegion
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    locationAddressRegion: prismic.KeyTextField;

    /**
     * Country field in *SchemaEvent → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Required
     * - **API ID Path**: schema_event.primary.locationAddressCountry
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    locationAddressCountry: prismic.KeyTextField;

    /**
     * Location URL field in *SchemaEvent → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: schema_event.primary.locationUrl
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    locationUrl: prismic.KeyTextField;

    /**
     * Include offer field in *SchemaEvent → Primary*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: schema_event.primary.include_offer
     * - **Documentation**: https://prismic.io/docs/field#boolean
     */
    include_offer: prismic.BooleanField;

    /**
     * Offer availability field in *SchemaEvent → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: In stock
     * - **API ID Path**: schema_event.primary.offerAvailability
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    offerAvailability: prismic.SelectField<'In stock' | 'Sold out' | 'Pre-order', 'filled'>;

    /**
     * Price field in *SchemaEvent → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: schema_event.primary.offerPrice
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    offerPrice: prismic.KeyTextField;

    /**
     * Currency field in *SchemaEvent → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: schema_event.primary.offerPriceCurrency
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    offerPriceCurrency: prismic.KeyTextField;

    /**
     * Price valid from date & time field in *SchemaEvent → Primary*
     *
     * - **Field Type**: Timestamp
     * - **Placeholder**: *None*
     * - **API ID Path**: schema_event.primary.offerValidFrom
     * - **Documentation**: https://prismic.io/docs/field#timestamp
     */
    offerValidFrom: prismic.TimestampField;

    /**
     * Offer URL field in *SchemaEvent → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: schema_event.primary.offerUrl
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    offerUrl: prismic.KeyTextField;

    /**
     * Included Organiser field in *SchemaEvent → Primary*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: schema_event.primary.included_organiser
     * - **Documentation**: https://prismic.io/docs/field#boolean
     */
    included_organiser: prismic.BooleanField;

    /**
     * Organiser Type field in *SchemaEvent → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: Person
     * - **API ID Path**: schema_event.primary.organiserPerformerType
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    organiserPerformerType: prismic.SelectField<'Person' | 'PerformingGroup', 'filled'>;

    /**
     * Organiser Name field in *SchemaEvent → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: schema_event.primary.organiserName
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    organiserName: prismic.KeyTextField;

    /**
     * Organiser URL field in *SchemaEvent → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: schema_event.primary.organiserUrl
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    organiserUrl: prismic.KeyTextField;

    /**
     * Include performer field in *SchemaEvent → Primary*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: schema_event.primary.include_performer
     * - **Documentation**: https://prismic.io/docs/field#boolean
     */
    include_performer: prismic.BooleanField;

    /**
     * Performer Type field in *SchemaEvent → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: Person
     * - **API ID Path**: schema_event.primary.performerType
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    performerType: prismic.SelectField<'Person' | 'PerformingGroup', 'filled'>;

    /**
     * Performer Name field in *SchemaEvent → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: schema_event.primary.performerName
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    performerName: prismic.KeyTextField;
}

/**
 * Default variation for SchemaEvent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SchemaEventSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<SchemaEventSliceDefaultPrimary>,
    never
>;

/**
 * Slice variation for *SchemaEvent*
 */
type SchemaEventSliceVariation = SchemaEventSliceDefault;

/**
 * SchemaEvent Shared Slice
 *
 * - **API ID**: `schema_event`
 * - **Description**: SchemaEvent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SchemaEventSlice = prismic.SharedSlice<'schema_event', SchemaEventSliceVariation>;

/**
 * Primary content in *SchemaFaq → Items*
 */
export interface SchemaFaqSliceDefaultItem {
    /**
     * Question field in *SchemaFaq → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: schema_faq.items[].question
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    question: prismic.KeyTextField;

    /**
     * Answer field in *SchemaFaq → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: schema_faq.items[].answer
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    answer: prismic.KeyTextField;
}

/**
 * Default variation for SchemaFaq Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SchemaFaqSliceDefault = prismic.SharedSliceVariation<
    'default',
    Record<string, never>,
    Simplify<SchemaFaqSliceDefaultItem>
>;

/**
 * Slice variation for *SchemaFaq*
 */
type SchemaFaqSliceVariation = SchemaFaqSliceDefault;

/**
 * SchemaFaq Shared Slice
 *
 * - **API ID**: `schema_faq`
 * - **Description**: SchemaFaq
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SchemaFaqSlice = prismic.SharedSlice<'schema_faq', SchemaFaqSliceVariation>;

/**
 * Primary content in *SchemaOrganisation → Primary*
 */
export interface SchemaOrganisationSliceDefaultPrimary {
    /**
     * Type field in *SchemaOrganisation → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: Airline
     * - **API ID Path**: schema_organisation.primary.type
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    type: prismic.SelectField<
        | 'Airline'
        | 'Consortium'
        | 'Corporation'
        | 'Educational Organization > ElementarySchool'
        | 'Educational Organization > HighSchool'
        | 'Educational Organization > MiddleSchool'
        | 'Educational Organization > PreSchool'
        | 'Educational Organization > School'
        | 'Educational Organization > Other'
        | 'FundingScheme'
        | 'GovernmentOrganization'
        | 'LibrarySystem'
        | 'MedicalOrganization'
        | 'NGO'
        | 'NewsMediaOrganization > Dentist'
        | 'NewsMediaOrganization > DiagnosticLab'
        | 'NewsMediaOrganization > Hospital'
        | 'NewsMediaOrganization > MedicalClinic'
        | 'NewsMediaOrganization > Pharmacy'
        | 'NewsMediaOrganization > Physician'
        | 'NewsMediaOrganization > VeterinaryCare'
        | 'NewsMediaOrganization > Other'
        | 'Organization'
        | 'PerformingGroup > DanceGroup'
        | 'PerformingGroup > MusicGroup'
        | 'PerformingGroup > TheaterGroup'
        | 'PerformingGroup > Other'
        | 'Project > FundingAgency'
        | 'Project > ResearchProject'
        | 'Project > Other'
        | 'SportsOrganization > SportsTeam'
        | 'SportsOrganization > Other'
        | 'WorkersUnion',
        'filled'
    >;

    /**
     * Name field in *SchemaOrganisation → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Required
     * - **API ID Path**: schema_organisation.primary.name
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    name: prismic.KeyTextField;

    /**
     * Logo URL field in *SchemaOrganisation → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Required
     * - **API ID Path**: schema_organisation.primary.logo
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    logo: prismic.KeyTextField;

    /**
     * Website URL field in *SchemaOrganisation → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Required
     * - **API ID Path**: schema_organisation.primary.url
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    url: prismic.KeyTextField;

    /**
     * Street Address field in *SchemaOrganisation → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Required
     * - **API ID Path**: schema_organisation.primary.streetAddress
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    streetAddress: prismic.KeyTextField;

    /**
     * City field in *SchemaOrganisation → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Required
     * - **API ID Path**: schema_organisation.primary.addressLocality
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    addressLocality: prismic.KeyTextField;

    /**
     * State/Province/Region field in *SchemaOrganisation → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Required
     * - **API ID Path**: schema_organisation.primary.addressRegion
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    addressRegion: prismic.KeyTextField;

    /**
     * Country field in *SchemaOrganisation → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Required
     * - **API ID Path**: schema_organisation.primary.addressCountry
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    addressCountry: prismic.KeyTextField;

    /**
     * Include social profiles field in *SchemaOrganisation → Primary*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: schema_organisation.primary.include_social_profiles
     * - **Documentation**: https://prismic.io/docs/field#boolean
     */
    include_social_profiles: prismic.BooleanField;

    /**
     * Facebook field in *SchemaOrganisation → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: schema_organisation.primary.facebook
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    facebook: prismic.KeyTextField;

    /**
     * Instagram field in *SchemaOrganisation → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: schema_organisation.primary.instagram
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    instagram: prismic.KeyTextField;

    /**
     * LinkedIn field in *SchemaOrganisation → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: schema_organisation.primary.linkedin
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    linkedin: prismic.KeyTextField;

    /**
     * Twitter field in *SchemaOrganisation → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: schema_organisation.primary.twitter
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    twitter: prismic.KeyTextField;
}

/**
 * Default variation for SchemaOrganisation Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SchemaOrganisationSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<SchemaOrganisationSliceDefaultPrimary>,
    never
>;

/**
 * Slice variation for *SchemaOrganisation*
 */
type SchemaOrganisationSliceVariation = SchemaOrganisationSliceDefault;

/**
 * SchemaOrganisation Shared Slice
 *
 * - **API ID**: `schema_organisation`
 * - **Description**: SchemaOrganisation
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SchemaOrganisationSlice = prismic.SharedSlice<'schema_organisation', SchemaOrganisationSliceVariation>;

/**
 * Primary content in *SchemaWebsiteSiteLinks → Primary*
 */
export interface SchemaWebsiteSiteLinksSliceDefaultPrimary {
    /**
     * URL field in *SchemaWebsiteSiteLinks → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Required
     * - **API ID Path**: schema_website_site_links.primary.url
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    url: prismic.KeyTextField;

    /**
     * Sitesearch URL field in *SchemaWebsiteSiteLinks → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Required
     * - **API ID Path**: schema_website_site_links.primary.target
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    target: prismic.KeyTextField;
}

/**
 * Default variation for SchemaWebsiteSiteLinks Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SchemaWebsiteSiteLinksSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<SchemaWebsiteSiteLinksSliceDefaultPrimary>,
    never
>;

/**
 * Slice variation for *SchemaWebsiteSiteLinks*
 */
type SchemaWebsiteSiteLinksSliceVariation = SchemaWebsiteSiteLinksSliceDefault;

/**
 * SchemaWebsiteSiteLinks Shared Slice
 *
 * - **API ID**: `schema_website_site_links`
 * - **Description**: SchemaWebsiteSiteLinks
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SchemaWebsiteSiteLinksSlice = prismic.SharedSlice<
    'schema_website_site_links',
    SchemaWebsiteSiteLinksSliceVariation
>;

/**
 * Primary content in *TestDelete → Primary*
 */
export interface TestDeleteSliceDefaultPrimary {
    /**
     * Title field in *TestDelete → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: test_delete.primary.title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField;
}

/**
 * Default variation for TestDelete Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestDeleteSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<TestDeleteSliceDefaultPrimary>,
    never
>;

/**
 * Slice variation for *TestDelete*
 */
type TestDeleteSliceVariation = TestDeleteSliceDefault;

/**
 * TestDelete Shared Slice
 *
 * - **API ID**: `test_delete`
 * - **Description**: TestDelete
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestDeleteSlice = prismic.SharedSlice<'test_delete', TestDeleteSliceVariation>;

/**
 * Primary content in *TextBlock → Primary*
 */
export interface TextBlockSliceDefaultPrimary {
    /**
     * Content field in *TextBlock → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: text_block.primary.content
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    content: prismic.RichTextField;
}

/**
 * Default variation for TextBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<TextBlockSliceDefaultPrimary>,
    never
>;

/**
 * Slice variation for *TextBlock*
 */
type TextBlockSliceVariation = TextBlockSliceDefault;

/**
 * TextBlock Shared Slice
 *
 * - **API ID**: `text_block`
 * - **Description**: TextBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSlice = prismic.SharedSlice<'text_block', TextBlockSliceVariation>;

declare module '@prismicio/client' {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }

    namespace Content {
        export type {
            CategoryDocument,
            CategoryDocumentData,
            CategoryDocumentDataSlicesSlice,
            FootermenuDocument,
            FootermenuDocumentData,
            FootermenuDocumentDataNavigationItem,
            GlobaloptionsDocument,
            GlobaloptionsDocumentData,
            GlobaloptionsDocumentDataAddressItem,
            HomepageDocument,
            HomepageDocumentData,
            HomepageDocumentDataSlicesSlice,
            HomepageDocumentDataSlices1Slice,
            HomepageDocumentDataSlices2Slice,
            PageDocument,
            PageDocumentData,
            PageDocumentDataSlicesSlice,
            PageDocumentDataSlices1Slice,
            PageDocumentDataSlices2Slice,
            PostDocument,
            PostDocumentData,
            PostDocumentDataSlicesSlice,
            PostDocumentDataSlices1Slice,
            PostDocumentDataSlices2Slice,
            PostsDocument,
            PostsDocumentData,
            PostsDocumentDataSlicesSlice,
            PostsDocumentDataSlices1Slice,
            PrimarymenuDocument,
            PrimarymenuDocumentData,
            PrimarymenuDocumentDataNavigationItem,
            SocialplatformsDocument,
            SocialplatformsDocumentData,
            AllDocumentTypes,
            ClientGridSlice,
            ClientGridSliceDefaultItem,
            ClientGridSliceVariation,
            ClientGridSliceDefault,
            ContactFormSlice,
            ContactFormSliceVariation,
            ContactFormSliceDefault,
            FeaturesGridSlice,
            FeaturesGridSliceDefaultPrimary,
            FeaturesGridSliceDefaultItem,
            FeaturesGridSliceVariation,
            FeaturesGridSliceDefault,
            HerotextSlice,
            HerotextSliceDefaultPrimary,
            HerotextSliceDefaultItem,
            HerotextSliceHeroTextWithVideoPrimary,
            HerotextSliceHeroTextWithVideoItem,
            HerotextSliceVariation,
            HerotextSliceDefault,
            HerotextSliceHeroTextWithVideo,
            LeadGenFormSlice,
            LeadGenFormSliceVariation,
            LeadGenFormSliceDefault,
            SchemaArticleSlice,
            SchemaArticleSliceDefaultPrimary,
            SchemaArticleSliceVariation,
            SchemaArticleSliceDefault,
            SchemaEventSlice,
            SchemaEventSliceDefaultPrimary,
            SchemaEventSliceVariation,
            SchemaEventSliceDefault,
            SchemaFaqSlice,
            SchemaFaqSliceDefaultItem,
            SchemaFaqSliceVariation,
            SchemaFaqSliceDefault,
            SchemaOrganisationSlice,
            SchemaOrganisationSliceDefaultPrimary,
            SchemaOrganisationSliceVariation,
            SchemaOrganisationSliceDefault,
            SchemaWebsiteSiteLinksSlice,
            SchemaWebsiteSiteLinksSliceDefaultPrimary,
            SchemaWebsiteSiteLinksSliceVariation,
            SchemaWebsiteSiteLinksSliceDefault,
            TestDeleteSlice,
            TestDeleteSliceDefaultPrimary,
            TestDeleteSliceVariation,
            TestDeleteSliceDefault,
            TextBlockSlice,
            TextBlockSliceDefaultPrimary,
            TextBlockSliceVariation,
            TextBlockSliceDefault,
        };
    }
}
