// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
    client_grid: dynamic(() => import('./ClientGrid')),
    contact_form: dynamic(() => import('./ContactForm')),
    features_grid: dynamic(() => import('./FeaturesGrid')),
    herotext: dynamic(() => import('./HeroText')),
    lead_gen_form: dynamic(() => import('./LeadGenForm')),
    schema_article: dynamic(() => import('./SchemaArticle')),
    schema_event: dynamic(() => import('./SchemaEvent')),
    schema_faq: dynamic(() => import('./SchemaFaq')),
    schema_organisation: dynamic(() => import('./SchemaOrganisation')),
    schema_website_site_links: dynamic(() => import('./SchemaWebsiteSiteLinks')),
    test_delete: dynamic(() => import('./TestDelete')),
    text_block: dynamic(() => import('./TextBlock')),
};
